apps/utilities/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('repository_detail/<int:repository_id>/', views.repository_detail, name='repository_detail'),
    path('history/', views.history, name="history"),
    path('add_repository/<int:folder_id>/', views.add_repository, name='add_repository_with_folder'),
    path('search_repository/', views.search_repository, name='search_repository'),
    path('save_repository/', views.save_repository, name='save_repository'),
    path('delete_repository/<int:repository_id>/', views.delete_repository, name='delete_repository'),
    path('delete_folder/<int:folder_id>/', views.delete_folder, name='delete_folder'),
]

gittrackr/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("__reload__", include("django_browser_reload.urls")),
    path('', views.index, name="landingPage"),
    path('logged/', views.indexLogged, name="loggedHomepage"),
    path('accounts/', include('apps.accounts.urls')),
    path('comparison/', include('apps.comparison.urls')),
    path('utilities/', include('apps.utilities.urls')),

    path('create_folder/', views.create_folder, name='create_folder'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/utilities/models.py
from django.db import models

#Create your models in here.

master/models.py
from django.db import models
from django.contrib.auth.models import User

class Folders(models.Model):
    FolderID = models.AutoField(primary_key=True)
    Folder_Name = models.CharField(max_length=255, unique=True)
    Created_At = models.DateTimeField(auto_now_add=True)
    UserID = models.ForeignKey(User, on_delete=models.CASCADE)

class Repository(models.Model):
    RepositoryID = models.AutoField(primary_key=True)
    Repository_Name = models.CharField(max_length=255, unique=True)
    Owner = models.CharField(max_length=255, null=True)
    Url = models.TextField()
    Folder_ID = models.ForeignKey(Folders, on_delete=models.CASCADE, null=True, blank=True)

class History(models.Model):
    HistoryID = models.AutoField(primary_key=True)
    Timestap = models.DateTimeField()
    UserID = models.ForeignKey(User, on_delete=models.CASCADE)
    FolderID = models.ForeignKey(Folders, on_delete=models.CASCADE)

apps/utilities/forms.py
# forms.py
from django import forms

class AddRepositoryForm(forms.Form):
    repository_name = forms.CharField(
        label='',
        max_length=100,
        widget=forms.TextInput(attrs={'class': 'w-96 mx-4 border-2 rounded-xl m-4', 'placeholder' : 'ex. DjangoEcommerce'},)
        )

apps/utilities/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.contrib import messages
from django.http import JsonResponse
from datetime import datetime, timedelta
from github import Github

from .forms import AddRepositoryForm
from master.models import Repository, Folders

import requests
import json

@login_required
def repository_detail(request, repository_id):
    repo = Repository.objects.get(RepositoryID=repository_id)

    g = Github(settings.GITHUB_TOKEN)

    github_repo = g.get_repo(f"{repo.Owner}/{repo.Repository_Name}")

    languages = github_repo.get_languages()
    total_bytes = sum(languages.values())
    formatted_languages = {lang: f"{(bytes / total_bytes) * 100:.1f}%" for lang, bytes in languages.items()}

    details = {
        'Repository_Name': repo.Repository_Name,
        'Owner_Name': repo.Owner,
        'About': github_repo.description,
        'Languages': formatted_languages,
        'File_Size': github_repo.size,
        'Date_Created': github_repo.created_at,
        'Topics': github_repo.get_topics(),
        'Branch': github_repo.default_branch,
        'Contributors': [contributor.login for contributor in github_repo.get_contributors()],
        'Stars': github_repo.stargazers_count,
        'CountCommit': json.dumps(get_github_data(github_repo)),
        'CountPullreq': json.dumps(count_pull_requests(github_repo)),
    }

    return render(request, 'utilities/repository_detail.html', {'details': details, 'repository_id': repository_id})


def get_github_data(repo):
    commit_count_data = {}

    for commit in repo.get_commits():
        timestamp = commit.commit.author.date.timestamp()
        commit_date = datetime.fromtimestamp(timestamp)
        month_year = commit_date.strftime('%Y-%m')
        contributor = commit.commit.author.name

        if month_year not in commit_count_data:
            commit_count_data[month_year] = {'total': 0, 'contributors': {}}

        commit_count_data[month_year]['total'] += 1

        if contributor not in commit_count_data[month_year]['contributors']:
            commit_count_data[month_year]['contributors'][contributor] = 1
        else:
            commit_count_data[month_year]['contributors'][contributor] += 1
        
    return commit_count_data

def count_pull_requests(repo):
    pull_requests = repo.get_pulls(state='all')
    pull_request_count_data = {}

    for pull_request in pull_requests:
        timestamp = pull_request.created_at.timestamp()
        pull_request_date = datetime.fromtimestamp(timestamp)
        month_year = pull_request_date.strftime('%Y-%m')
        contributor = pull_request.user.login

        if month_year not in pull_request_count_data:
            pull_request_count_data[month_year] = {'total': 0, 'contributors': {}}
        pull_request_count_data[month_year]['total'] += 1

        if contributor not in pull_request_count_data[month_year]['contributors']:
            pull_request_count_data[month_year]['contributors'][contributor] = 1
        else:
            pull_request_count_data[month_year]['contributors'][contributor] += 1

    return pull_request_count_data

@login_required
def history(request):
    folders = Folders.objects.filter(UserID=request.user)
    return render(request, 'utilities/history.html', {'folders': folders})

@login_required
def delete_folder(request, folder_id):
    folder = Folders.objects.get(FolderID=folder_id, UserID=request.user)
    folder.delete()


    return redirect('history')

@login_required
def add_repository(request, folder_id=None):
    if folder_id is not None:
        request.session['current_folder_id'] = folder_id

    folder_id = request.session.get('current_folder_id')
    folder = Folders.objects.get(FolderID=folder_id)
    
    # Mengambil semua repositori dalam folder ini
    saved_repositories = Repository.objects.filter(Folder_ID=folder)

    form = AddRepositoryForm()
    folders = Folders.objects.all()
    return render(request, 'utilities/add_repository.html', {'form': form, 'folder': folder, 'folders': folders, 'save_repository': saved_repositories})

@login_required
def delete_repository(request, repository_id):
    try:
        repository = Repository.objects.get(RepositoryID=repository_id)
        folder_id = repository.Folder_ID_id  # Simpan ID folder untuk redirect
        repository.delete()
        messages.success(request, "Repository berhasil dihapus.")
    except Repository.DoesNotExist:
        messages.error(request, "Repository tidak ditemukan.")

    return redirect('add_repository_with_folder', folder_id=folder_id)


@login_required
def search_repository(request):
    if request.method == 'POST':
        form = AddRepositoryForm(request.POST)
        if form.is_valid():
            full_repository_name = form.cleaned_data['repository_name']

            headers = {'Authorization': f'token {settings.GITHUB_TOKEN}'}
            url = f'https://api.github.com/search/repositories?q={full_repository_name}'
            response = requests.get(url, headers=headers)

            folder_id = request.session.get('current_folder_id')
            folder = Folders.objects.get(FolderID=folder_id)

            # Menambahkan saved_repositories ke konteks
            saved_repositories = Repository.objects.filter(Folder_ID=folder)

            if response.status_code == 200:
                form = AddRepositoryForm()
                data = response.json()
                repositories = data.get('items', [])

                for repository in repositories:
                    repository['repository_owner'], repository['repository_name'] = repository['full_name'].split('/')

                return render(request, 'utilities/add_repository.html', {'form': form, 'repositories': repositories, 'folder': folder, 'save_repository': saved_repositories})
            else:
                messages.error(request, f'Error {response.status_code}: {response.text}')

    return redirect('add_repository')

@login_required
def save_repository(request):
    if request.method == 'POST':
        repository_name = request.POST.get('repository_name')
        owner = request.POST.get('repository_owner')
        repository_url = request.POST.get('repository_url')
        folder_id = request.session.get('current_folder_id')

        if Repository.objects.filter(Repository_Name=repository_name, Folder_ID_id=folder_id, Url=repository_url).exists():
            messages.error(request, 'Repositori ini sudah ada di folder ini.')
            return redirect('add_repository_with_folder', folder_id=folder_id)

        repository = Repository(Owner=owner, Repository_Name=repository_name, Url=repository_url, Folder_ID_id=folder_id)
        repository.save()

    return redirect('add_repository_with_folder', folder_id=folder_id)

templates/utilities/add_repository.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Repository</title>
    {% tailwind_css %}
    <style>
        #loadingSpinner {
            z-index: 10;
        }
        .spinner {
            border: 4px solid rgba(255, 9, 9, 0.587);
            border-radius: 50%;
            border-top: 4px solid #fff;
            width: 50px;
            height: 50px;
            -webkit-animation: spin 1s linear infinite; /* Safari */
            animation: spin 1s linear infinite;
            position: fixed;
        }

        /* Safari */
        @-webkit-keyframes spin {
            0% { -webkit-transform: rotate(0deg); }
            100% { -webkit-transform: rotate(360deg); }
        }
    
        @keyframes spin {
            0% { transform: rotate(0deg); }
            100% { transform: rotate(360deg); }
        }
    </style>
</head>

<body class="overflow-x-hidden">

    {% block section %}
    {% include "component/navbar_logged.html" %}
    {% endblock %}

    <!-- Loading Spinner -->
    <div id="loadingSpinner" class="fixed inset-0 bg-gray-700 bg-opacity-50 flex justify-center items-center hidden ">
        <div class="spinner"></div>
    </div>

    <div class="relative flex flex-row py-40 justify-center">

        <div class="bg-white mx-28 border-2 rounded-xl h-fit">
            <div class="border-b-2 px-4 py-4">
                <h1 class="text-black text-xl font-bold">{{ folder.Folder_Name }}'s Folder</h1>
            </div>

            <div class="flex items-center px-4 py-4">
                <!-- SVG Icon -->
                <svg width="44" height="53" viewBox="0 0 54 63" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path
                        d="M9.66992 49.8131V13.149C9.66992 11.7599 10.1364 10.4276 10.9669 9.44535C11.7973 8.46309 12.9236 7.91125 14.098 7.91125H43.7658C44.1181 7.91125 44.456 8.0768 44.7051 8.37148C44.9542 8.66616 45.0942 9.06583 45.0942 9.48257V43.8264"
                        stroke="black" stroke-width="1.5" stroke-linecap="round" />
                    <path d="M34.0242 44.5753V57.6696L39.5592 53.4795L45.0942 57.6696V44.5753" stroke="black"
                        stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
                    <path d="M14.0979 44.5753H45.0941" stroke="black" stroke-width="1.5" stroke-linecap="round" />
                    <path
                        d="M14.098 44.5753C12.9236 44.5753 11.7973 45.1271 10.9669 46.1094C10.1364 47.0917 9.66992 48.4239 9.66992 49.813C9.66992 51.2022 10.1364 52.5344 10.9669 53.5167C11.7973 54.4989 12.9236 55.0508 14.098 55.0508H26.275"
                        stroke="black" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
                </svg>
                <!-- Repository Title -->
                <p class="px-2 text-center text-black text-xl font-semibold">Add repository</p>
            </div>

            <!-- Input Repository Form -->
            <div class="py-4 px-2 w-[450px]">
                <form method="post" action="{% url 'search_repository' %}">
                    {% csrf_token %}
                    {{ form.repository_name }}
                    <input type="submit" value="Submit"
                        class="m-4 py-2 px-4 border border-black rounded-xl hover:bg-gray-100 hover:border-gray-500">
                </form>
            </div>

            <!-- Maximum 5 Repositories Display -->
            <div class="border-t-2 my-4 px-4 justify-center items-center">
                <p class="my-4 text-black text-xs font-extralight font-['Montserrat']">Repositori dalam Folder:</p>
                <div id="repositoryContainer" class="grid gap-2 grid-cols-2 col-auto row-auto auto-cols-max auto-rows-max">
                    {% for repository in save_repository %}
                    <div class="flex justify-between items-center">
                        <p>{{ repository.Repository_Name }}</p>
                        <!-- Formulir untuk menghapus repositori -->
                        <form method="post" action="{% url 'delete_repository' repository.RepositoryID %}">
                            {% csrf_token %}
                            <button type="submit" class="bg-red-500 text-white px-3 py-1 rounded-full">x</button>
                        </form>
                    </div>
                    {% empty %}
                    <p>Tidak ada repositori dalam folder ini.</p>
                    {% endfor %}
                </div>
            </div>

            <!-- Button Actions -->
            <div class="flex px-8 py-4 border-t-2 justify-between">
                <button type="button" class="bg-white border py-2 px-6 rounded-2xl border-black">
                    <p class="text-center text-black text-lg font-semibold">Cancel</p>
                </button>
                <button type="button" class="bg-black border py-2 px-4 rounded-2xl border-black">
                    <a href="{% url 'compare_repositories' folder.FolderID %}"
                        class="text-center text-white text-lg font-semibold">Compare</a>
                </button>
            </div>
        </div>

        <!-- Repository List -->
        <div>
            <ul class="grid grid-cols-2">
                {% for repository in repositories %}
                <li class="py-2 mx-2">
                    <div class="bg-white shadow-lg rounded-lg p-2">
                        <strong class="text-md py-1 px-2">{{ repository.repository_name }}</strong><br>
                        <strong class="text-xs py-1 px-2">Owner:</strong><br>
                        <strong class="text-xs py-1 px-2">{{ repository.repository_owner }}</strong>
                        <form method="post" action="{% url 'save_repository' %}">
                            {% csrf_token %}
                            <input type="hidden" name="repository_name" value="{{ repository.repository_name }}">
                            <input type="hidden" name="repository_owner" value="{{ repository.repository_owner }}">
                            <input type="hidden" name="repository_url" value="{{ repository.html_url }}">
                            <button type="submit"
                                class="my-2 py-1 px-2 border text-xs border-black rounded-lg hover:bg-gray-100 hover:border-gray-500 add-to-folder-button">Add
                                to My Folder</button>
                        </form>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>

        <!-- Display Messages -->
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}

    </div>

    <!-- JavaScript -->
    <script>
        document.addEventListener("DOMContentLoaded", function () {
                const dropdownButton = document.querySelector(".group");
                const dropdownMenu = document.querySelector(".absolute");

                dropdownButton.addEventListener("click", function () {
                    dropdownMenu.classList.toggle("hidden");
                });
        });

        document.addEventListener('DOMContentLoaded', function() {
            const compareButton = document.querySelector('a[href*="compare_repositories"]');
            const loadingSpinner = document.getElementById('loadingSpinner');

            compareButton.addEventListener('click', function() {
                loadingSpinner.classList.remove('hidden');
            });
        });
    </script>
</body>
</html>

templates/utilities/history.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>History</title>
    {% tailwind_css %}
</head>

<body>
    <!-- Navbar Start -->
    {% block section %}
    {% include "component/navbar_logged.html" %}
    {% endblock %}
    <!-- Navbar End -->

    <!-- Content Start -->
    <div class="flex justify-end pr-32 ">
        <input type="text" class="w-96 border border-gray-300 rounded-lg p-2" placeholder="Search..">
    </div>
    <div class="py-4 mt-12 px-28">
        
    </div>
    <div class="py-4 px-28">
        <h1 class="text-black text-2xl font-medium py-2 ml-2">
            Recently
        </h1>
        <div class="flex flex-wrap">
            {% for folder in folders %}
            <div class="bg-sky-100 px-4 py-2 w-full rounded-xl shadow-lg m-2 relative">
                <a href="{% url 'add_repository_with_folder' folder_id=folder.FolderID %}" class="block">
                    <div class="flex flex-col justify-between">
                        <div class="flex items-center">
                            <h1 class="text-black text-xl font-medium">Folder name: <b>{{ folder.Folder_Name }}</b> </h1>
                        </div>
                        <div class="flex items-center">
                            <p>Created at: <b>{{ folder.Created_At|date:"d F Y" }}</b></p>
                        </div>
                        <div class="">
                            <p class="text-black text-xl font-bold leading-9 py-2">
                                Repositories List:
                            </p>
                            <ul class="list-disc text-black text-xs font-normal px-5">
                                {% for repository in folder.repository_set.all %}
                                <li>
                                    {{ repository.Owner }} / {{ repository.Repository_Name }}
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </a>
                <!-- Tombol Hapus Folder -->
                <form method="post" action="{% url 'delete_folder' folder.FolderID %}" class="absolute top-2 right-2">
                    {% csrf_token %}
                    <button type="submit" class="bg-red-500 hover:bg-red-600 text-white px-3 py-1 rounded-full text-sm">Hapus Folder</button>
                </form>
            </div>
            {% endfor %}
        </div>
    </div>

        <script>
            document.addEventListener("DOMContentLoaded", function () {
                const dropdownButton = document.querySelector(".group");
                const dropdownMenu = document.querySelector(".absolute");

                dropdownButton.addEventListener("click", function () {
                    dropdownMenu.classList.toggle("hidden");
                });
            });
        </script>
</body>

</html>